# Changes here will be overwritten by Copier
_commit: 0.6.1
_src_path: https://github.com/nlesc/python-template.git
copyright_holder: Koen Nijbroek
email: koennijbroek@gmail.com
full_name: Koen Nijbroek
github_organization: coryza
keywords: dessert,sweet,fake,remove
license: Apachev2
package_name: baklava
package_short_description: A sweet package
template_profile: minimum
version: 0.1.0
